### ISSUE TITLE
USDPL or PowerTools's backend did not start correctly!

### ISSUE THREAD

**Issue by Anguspeters** [NGnius/PowerTools#95] opened 2023-04-12 01:33 UTC
### Please confirm

- [x] I have searched existing issues
- [x] This issue is not a duplicate of an existing one
- [x] I will fill this out to the best of my ability

### Expected Behaviour

PowerTool's should open regularly.

### Actual Behaviour

Everytime I hit the PowerTools tab it says USDPL or PowerTools's backend did not start correctly. I have tried reinstalling both decky and powertools, as well as restarts.

### Steps To Reproduce

Open Powertools

### Version

1.3.1 (Latest stable)

### Platform

Steam Deck

### OS

SteamOS 3 (Stable)

**Comment by NGnius** [comment] 2023-04-12 21:31
Looks like there's an issue with the v1.3.1 version on the default store. Awaiting a fix for the CI

**Comment by NGnius** [comment] 2023-04-12 21:52
In the meantime, you can fix it by running this command.
```bash
sudo chmod +x -R ~/homebrew/plugins/PowerTools/bin/
```
(The problem is the backend doesn't start because it's not marked as executable)

**Comment by NGnius** [comment] 2023-04-15 03:45
This should be fixed on the store with version `v1.3.1-1`

**Closed by NGnius** 2023-04-15 03:45 UTC
Labels: bug

**Comment by MarcoLP1822** [comment] 2023-06-19 11:42
I've just installed PowerTools for the first time 1.3.2 and I have this exact issue
