### ISSUE TITLE
Plugged in TDP unlock and max clock

### ISSUE THREAD

**Issue by m4rshm4ll0w** [NGnius/PowerTools#102] opened 2023-05-12 16:20 UTC
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I will fill this out to the best of my ability

### Describe what you'd like to be able to do

I believe that the ROG ally, when plugged into the wall will have increased performance. I talked about this to the CryoUtils discord and they recommended I reach out to you.

Feature idea is that the connection status is checked to if the deck is charging at high enough wattage, then automatically TDP will be unlocked, and max clocks will be set.
And once the deck is no longer docked/plugged in, then it would default back to the previous settings.

If possible. An overclock of some kind would be cool to automatically happen on plug in/when docked. But I'm not sure if that can be done without going into the bios each time?

Discord chats attached.
![image](https://github.com/NGnius/PowerTools/assets/133394382/ce22f277-6f09-4b87-a3c0-21c4e2a361a4)

### Describe alternatives you've considered

I've tried reaching out to CryoUtils already as I wasn't sure if they would be able to implement it in their program

**Comment by NGnius** [comment] 2023-05-16 16:28
Closing as duplicate of #82 to keep everything in one place

**Closed by NGnius** 2023-05-16 16:28 UTC
Labels: enhancement
