### ISSUE TITLE
Per window profile (emulation station)

### ISSUE THREAD

**Issue by francois-pasquier** [NGnius/PowerTools#117] opened 2023-07-30 11:20 UTC
### Please confirm

- [X] I have searched existing issues
- [ ] This issue is not a duplicate of an existing one
- [ ] I will fill this out to the best of my ability

### Describe what you'd like to be able to do

I am wondering if it would be achievable to use the current open window for linking the profile in some cases.

my use case is for running emulation station which opens different emulators. The profiles should be linked to the emulators and not emulation station itself.

is it even possible?

### Describe alternatives you've considered

For now I have to set the settings I want manually

**Comment by NGnius** [comment] 2023-07-30 16:54
This is a duplicate of #82 . I'm closing this in favour of that issue.

I have no intention of implementing this because you can (and probably should; it's really convenient) set up custom Steam games for every game or console you want to emulate.

**Closed as completed by NGnius** 2023-07-30 16:54 UTC
Labels: enhancement
