### ISSUE TITLE
Charge limit sets to 5000% on profile change

### ISSUE THREAD

**Issue by NorbiZsemi** [NGnius/PowerTools#96] opened 2023-04-12 20:54 UTC
### Please confirm

- [x] I have searched existing issues
- [x] This issue is not a duplicate of an existing one
- [x] I will fill this out to the best of my ability

### Expected Behaviour

The "Maximum (%)" value should remain consistent across game launches and cannot be more than 100%.

### Actual Behaviour

If I set a charge limit % and tick the "Persistent Profile" checkbox, the plugin always sets the percent 5000%. It happens after boot and If I launch a game. If I reset the value to for example 50%, then it resets to 5000 if I launch a different game or I exit to the main menu,

### Steps To Reproduce

1:  Charge limit checkbox = true
2: Maximum (%) = 50
3: Persistent Profile = true
4: Maximum (%) changes to 5000% upon launching or changing game / initial boot.

### Version

1.3.1 (Latest stable)

### Platform

Steam Deck

### OS

SteamOS 3 (Stable)

**Comment by NGnius** [comment] 2023-04-12 21:30
Duplicate of #91

**Closed by NGnius** 2023-04-12 21:30 UTC
Labels: bug, another one!
