### ISSUE TITLE
The program's configuration file generation does not use variables

### ISSUE THREAD

**Issue by danyi** [NGnius/PowerTools#57] opened 2022-12-25 05:58 UTC
When I use the user name "danyi", the configuration file of the program is still created in the "deck" directory, so the configuration file cannot be read, and the program crashes

**Comment by NGnius** [comment] 2022-12-25 14:08
This was caused by a bug in USDPL's utility lib, it should be fixed in the next update since that also includes a USDPL update. 

I'll leave this open until that update releases

**Closed** 2023-02-03 23:03 UTC
Labels: bug, v1.0, tbr
