### ISSUE TITLE
Powertools leaves behind .json config files even though persistent is turned off

### ISSUE THREAD

**Issue by claytankozmo** [NGnius/PowerTools#41] opened 2022-10-10 12:56 UTC
My config/powertools folder has a few json files that I cannot delete.

**Comment by NGnius** [comment] 2022-10-10 17:40
Yeah, I noticed this when trying to figure out the cause of #40. I have the fix implemented, I just haven't had time to test and release it

**Comment by NGnius** [comment] 2022-10-11 22:01
This should be fixed in v1.0.5

**Closed by NGnius** 2022-10-11 22:01 UTC
Labels: bug, indev, v1.0
