### ISSUE TITLE
Plugin Loader not changing threads and frequency. 

### ISSUE THREAD

**Issue by DeckyBoy** [NGnius/PowerTools#28] opened 2022-08-29 18:14 UTC
It's been stuck like that and deleting,uninstalling, or resetting has done nothing for me. I can't see the change in the smt toggle on and off as well as the frequency. I don't believe it works at all whether I change it to smt on or off and it may be related to the new update in deckyloader.

**Comment by NGnius** [comment] 2022-08-29 19:17
What version of PowerTools?

Also, did that same PowerTools version work before you updated Decky?

**Comment by nsoriau** [comment] 2022-09-02 19:18
I may be able to bring some details as I just experienced a similar issue.

I was using Decky version 2.0.5-pre14 and Powertools version 0.7.0, both Installed with EmuDeck a few weeks ago. I believe I have only been using Dolphin since I installed the latest version of Powertools, and it was working fine then. Today, I noticed I could only select 1 or 2 threads in Powertools, still while using Dolphin.

I tried reinstalling it through Decky and restarting the Steam Deck, but then Powertools became completely unresponsive (threads locked to 8, unable to change max. CPU frequency). I tried updating Decky to the latest version, but it didn't change much except the threads were now displaying "null" and the version changed to v0.00jank _(or something like this)_. I had the same behavior with all the emulators and steam games I tried.

I tried deleting and reinstalling Powertools through Decky again a few hours later (Steam Deck had been powered off since), and now everything is working again. I can change the max CPU frequency just fine, as well as the number of threads, and the version shows v0.7.0.

**Comment by NGnius** [comment] 2022-09-02 21:59
Thanks for the info, much appreciated!

From what you describe, it sounds like it's an issue with the back-end suddenly dying. With the re-write in the next release, I hope this won't happen since I'mmoving away from the regular Decky back-end implementation that has that known issue.

I don't think I can fix this before the re-write (and I'd also prefer not to be distracted with fixing an old version), so I'll leave this open until that's released.

**Comment by AndehX** [comment] 2022-09-03 11:25
having the same issue.  Power tools is just not working anymore, no matter how many times I install/uninstall decky loader.  None of the settings seem to do anything.

**Comment by daniel-dona** [comment] 2022-09-03 11:51
Same problem here

`sudo systemctl status plugin_loader.service`

```
● plugin_loader.service - SteamDeck Plugin Loader
     Loaded: loaded (/etc/systemd/system/plugin_loader.service; enabled; vendor preset: disabled)
     Active: active (running) since Sat 2022-09-03 13:48:38 CEST; 26s ago
   Main PID: 2618 (PluginLoader)
      Tasks: 21 (limit: 17714)
     Memory: 96.4M
        CPU: 1.275s
     CGroup: /system.slice/plugin_loader.service
             ├─2618 /home/deck/homebrew/services/PluginLoader
             ├─2623 /home/deck/homebrew/services/PluginLoader
             ├─2636 /home/deck/homebrew/services/PluginLoader
             ├─2639 /home/deck/homebrew/plugins/Fantastic/bin/backend
             ├─2668 /home/deck/homebrew/services/PluginLoader
             └─2669 /home/deck/homebrew/services/PluginLoader

Sep 03 13:48:39 steamdeck PluginLoader[2623]: [loader][INFO]: import plugins from /home/deck/homebrew/plugins
Sep 03 13:48:39 steamdeck PluginLoader[2623]: [loader][INFO]: found plugin: Fantastic
Sep 03 13:48:39 steamdeck PluginLoader[2623]: [loader][INFO]: Loaded Fantastic
Sep 03 13:48:39 steamdeck PluginLoader[2623]: [loader][INFO]: found plugin: PowerTools
Sep 03 13:48:39 steamdeck PluginLoader[2668]: [selector_events][DEBUG]: Using selector: EpollSelector
Sep 03 13:48:39 steamdeck PluginLoader[2623]: [loader][INFO]: Loaded PowerTools
Sep 03 13:48:39 steamdeck PluginLoader[2669]: [selector_events][DEBUG]: Using selector: EpollSelector
Sep 03 13:48:39 steamdeck PluginLoader[2670]: Starting back-end (fantastic-rs v0.3.3)
Sep 03 13:48:40 steamdeck PluginLoader[2670]: thread 'main' panicked at 'error binding to 127.0.0.1:44444: error creating server listener: Address already in use (os error 98)', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/warp-0.3.2/src/server.rs:213:27
Sep 03 13:48:40 steamdeck PluginLoader[2670]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by NGnius** [comment] 2022-09-03 14:25
I'd recommend y'all update to the latest version of Decky, if you haven't already. There has been some work to solve the back-end bug by Decky devs, but I'm not sure if it's completely fixed (I've never experienced this bug and I don't know how to reproduce it in order to test).

Also there is a similar bug that can look like this but isn't fixed by a restart/reinstall: PowerTools config corruption. You can fix that by deleting all your settings. The folder to delete is `~/.config/powertools/`, you may need superuser perms to delete it.

**Comment by KrisCris** [comment] 2022-09-04 18:21
I don't know if my issue is relevant... Suddenly I can't modify the number of threads, the slider is forced to 0.

**Comment by KrisCris** [comment] 2022-09-04 19:16
Alright... after removing the config and reloading, I can adjust the slider but I don't really think it's working. Those apps that I forced to have 5 threads are unable to get back to 8 threads, the usages of the first 5 threads are high while the rest 3 are idling all the time.

**Closed** 2022-09-09 02:10 UTC
Labels: bug, v0.7
