### ISSUE TITLE
PowerTools 0.7.0 (dev) can't change any settings after launching EmulationStation

### ISSUE THREAD

**Issue by OuterWinnie** [NGnius/PowerTools#17] opened 2022-07-04 23:30 UTC
**Expected Behaviour**
Settings should't get locked/hang when launching EmulationStation.

**Actual Behaviour**
It seems that PowerTools isn't able to detect what is being played and just says "Menu (Default)" in the "Now Playing" section, it's stuck in that state even if you close it and open another game. This also means that you can't change the settings anymore for some reason and you have to reboot to fix it.

**To Reproduce**
Just opening EmulationStation.

**Screenshots, etc.**
Please include the log (located at `/tmp/powertools.log`) if possible.
Note: the log is deleted when the device is restarted.

Video (sorry for the crappy quality):
https://streamable.com/q1nsxh
[PowerTools.log](https://github.com/NGnius/PowerTools/files/9042328/PowerTools.log)

**Comment by NGnius** [comment] 2022-07-05 02:45
Thanks for the report! Did you have a per-game profile set for emulation station before this update? If I had to guess, it's probably been corrupted and that's crashing PowerTools. Per-game profile settings are stored in `~/.config/powertools/` with filenames like `<app id>.json` if you want to try to find and/or delete the one for EmulationStation.

JSYK, that's not the correct log. Logs should start with something like this:
```
2022-07-04 22:35:45,750 INFO PowerTools v0.7.0-indev https://github.com/NGnius/PowerTools
2022-07-04 22:35:45,750 DEBUG CWD: /home/deck/homebrew/services HOME:/home/deck
2022-07-04 22:35:45,754 DEBUG Read `NAME="SteamOS"
PRETTY_NAME="SteamOS"
VERSION_CODENAME=holo
ID=steamos
ID_LIKE=arch
ANSI_COLOR="1;35"
HOME_URL="https://www.steampowered.com/"
DOCUMENTATION_URL="https://support.steampowered.com/"
SUPPORT_URL="https://support.steampowered.com/"
BUG_REPORT_URL="https://support.steampowered.com/"
LOGO=steamos
[...]
```

**Comment by OuterWinnie** [comment] 2022-07-05 11:32
I have deleted all the game profiles that i had, and it doesn't seems to be the problem.

I will leave you here the log, this is the right one?
[powertools.log](https://github.com/NGnius/PowerTools/files/9045960/powertools.log)

Thanks you for your work!

**Comment by NGnius** [comment] 2022-07-05 13:17
Yeah that's the right log now, thanks. That shows an error which is presumably caused by sending too much game metadata to PowerTools when EmulationStation is started. So yeah, deleting per-game profiles wouldn't have fixed it. Feel free to gloat.

Seems like an easy fix for me, I'll try to get that done later today.

**Comment by NGnius** [comment] 2022-07-05 23:43
Let me know if that latest dev version works better. I wasn't able to completely reproduce your issue, but I happened across something similar, which I fixed, along with reducing the amount of data sent to the back-end when a new game launches.

**Comment by OuterWinnie** [comment] 2022-07-06 16:30
Yep, it's fixed! Thanks!

There's another bug. If i have per example a game profile for EmulationStation (SMT Off, Boost Off), when i open the application, it applies the settings correctly but sometimes the powertools ui doesn't get updated to represent the changes. It also can happen when you close a game and get back to the menu.

Another video with crappy quality (i don't know how to record the screen in the game mode, sorry):
https://streamable.com/vw75oq

Should i open another issue to keep better track of it?

**Comment by NGnius** [comment] 2022-07-06 20:27
Oh yeah I noticed something like that while working on it yesterday. I thoight I'd fixed it along with the race condition I found, but apparently not.

Should be a quick fix too, don't worry about making a new issue

**Comment by NGnius** [comment] 2022-07-07 00:14
Alright, hopefully that should be fixed now too. Since you've been doing such a good job of testing stuff so far, want to try that fix out too?

**Comment by OuterWinnie** [comment] 2022-07-07 00:14
Yep, it's fully fixed now! Thanks you so much!

**Closed** 2022-07-07 00:19 UTC
Labels: bug
