### ISSUE TITLE
can you add a feature, manually set the maximum CPU frequency and GPU frequency？

### ISSUE THREAD

**Issue by FantasyGmm** [NGnius/PowerTools#75] opened 2023-02-20 11:29 UTC
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I will fill this out to the best of my ability

### Describe what you'd like to be able to do

Now we can overclock the CPU to 3700, so I wonder if there is a setting that can change the maximum frequency of the CPU frequency limit，The same is true for GPU
I overclock the CPU to 3700, turn off the SMT and manually limit the GPU frequency. I can run at a stable 30 frames in some games, but the current plug-in only allows me to adjust the frequency of 200-3500. Sometimes I don't set the frequency limit, and it will also limit my frequency to 3499

### Describe alternatives you've considered

I think it is a good plan to press and hold the button for modification. It should be just a front-end limitation

**Comment by NGnius** [comment] 2023-02-20 13:32
Duplicate of #53

**Closed by NGnius** 2023-02-20 13:32 UTC
Labels: another one!, enhancement
