### ISSUE TITLE
Automatically disable profile on charger toggle

### ISSUE THREAD

**Issue by Gamr13** [NGnius/PowerTools#105] opened 2023-05-16 07:52 UTC
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I will fill this out to the best of my ability

### Describe what you'd like to be able to do

Having the option (toggle) to disable the current profile automatically on charger would be fantastic, here’s why:

- Better performance without needing to worry about battery, if you’ve tuned PowerTools (PT) to account for battery. 

- Bypasses a bug with fullscreen UI / Game mode where the UI will refuse to appear on-screen without a restart 

- Generally a good QoL feature to have. 

### Describe alternatives you've considered

Button combinations to enable / disable profiles

**Comment by NGnius** [comment] 2023-05-16 16:23
Duplicate of #82

**Closed by NGnius** 2023-05-16 16:23 UTC
Labels: another one!, enhancement
