### ISSUE TITLE
Steam Deck hard shutdown when the maximum GPU clock is set lower and then the minimum GPU clock is set higher than the set maximum.

### ISSUE THREAD

**Issue by TeamLinux01** [NGnius/PowerTools#56] opened 2022-12-03 23:30 UTC
**Expected Behaviour**
The slider locks so the number cannot be set higher or lower depending on the other slider's value. The maximum slider cannot set lower than the minimum slider's value; the minimum slider cannot be set higher than the maximum slider's value.

**Actual Behaviour**
It is possible to move the minimum slider value to a number above what the maximum slider value is set to. When the minimum is set higher than the maximum, the Deck will hard power off.

**To Reproduce**
1. Change the GPU clock maximum to 1100
2. Change the GPU clock minimum to 1200
3. Deck powers off

**Extra notes**
This occurred because of another issue, there was a delay each setting change. I accidentally clicked it one too many times when changing the minimum.

**Comment by NGnius** [comment] 2022-12-04 04:12
I can't reproduce this. I actually allowed max < min because it was allowed by the kernel as well.

Since the deck reset logs won't be super helpful, but the rest of your settings (or the settings json) might be helpful.

**Comment by TeamLinux01** [comment] 2022-12-21 02:29
Sorry, I had to send my Steam Deck back to Valve on an unrelated issue with the left analog stick.

I should be receiving it back soon and then I can retest to see if I can reproduce the issue.

**Comment by NGnius** [comment] 2023-01-09 21:54
Have you managed to find a way to reproduce this or can I close this issue?

**Comment by TeamLinux01** [comment] 2023-01-09 22:18
I tried it again and this time when I did it, instead of hard poweroff, it crashed the steam overlay.

It had a message of "Something went while displaying this content. Refresh"

This is what I did:

*This can be done in a game or just on DeckUI

1. Press 3 dot button on the front of the deck.
2. Go to Decky.
3. Go to PowerTools.
4. Go to GPU Frequency Limits, click it on using D-Pad and A button.
5. Change Minimun (Mhz) to 900 from 200 using A button then Right D-Pad and then A button at 900.
6. Change Maximum (Mhz) to 800 from 1600 using A button then Left D-Pad.

Crashes as soon as it hits 900 or trying to go to 800 from 900 on Max.

**Comment by NGnius** [comment] 2023-01-10 00:37
Still cannot reproduce. Either there's something wrong with your Deck or it's been inadvertently fixed by other changes in the `dev` branch.

![image](https://user-images.githubusercontent.com/19637329/211435385-6f4a6858-72d5-4788-923a-2ce64fce243e.png)

In any case, I'm closing as it's either unreproduceable or solved. Since this is the only report I've had of this, I don't see much point in keeping it open until the next update releases.

**Closed by NGnius** 2023-01-10 00:37 UTC
Labels: bug, ???
